### ISSUE TITLE
No sscollector.pyz file

### ISSUE THREAD

**Issue by 2jclick** [Azure/Stormspotter#18]
The sscollector.pyz file was not in the stormcollector directory. I used the second setup to spin up the environment

**Comment by mdaslamansari** [comment]
second setup? Can you please clarify? Can you help me getting this file?

**Comment by legra-ms** [comment]
My bad! Typo in the Github action caused the wrong file to get zipped up. Fixing this now.

**Comment by legra-ms** [comment]
@2jclick @mdaslamansari Sorry about that.  The release has been reuploaded. https://github.com/Azure/Stormspotter/releases/tag/v1.0.0b

**Comment by MarkJaroski** [comment]
Using this release we're getting an error:

`AttributeError: module 'azure.identity' has no attribute 'AzureCliCredential'`


``

**Comment by MarkJaroski** [comment]
To follow up, it would appear that the shiv package prefers system libs over the ones in the package. I don't really know shiv so I'm not sure how to fix that, but to prove it to myself I did this:

`sudo mv /usr/lib/python3/dist-packages/azure/identity /usr/lib/python3/dist-packages/azure/identity.bak`

After which the error message change to this:

`ModuleNotFoundError: No module named 'azure.mgmt.resource.resources.aio'`

**Comment by MarkJaroski** [comment]
It works if you run it with the full path to python and -S. I don't know if this could be made to be the default behaviour:

`/usr/bin/python3.8 -S sscollector.pyz cli`

**Comment by legra-ms** [comment]
@MarkJaroski I'm going to close this particular issue and move this conversation over to more related one here: https://github.com/Azure/Stormspotter/issues/20
