### ISSUE TITLE
python3 sscollector.pyz cli error

### ISSUE THREAD

**Issue by mdaslamansari** [Azure/Stormspotter#21]
Hi,

While running above command, i got below log and the results zip is created. When I am trying to upload this results zip in FE, i am getting some error. Results zip took good amount of time to get generated -

Log -
```
2020-09-09 13:30:29.063 | ERROR    | asyncio.events:_run:81 - An error has been caught in function '_run', process 'MainProcess' (5661), thread 'MainThread' (140196066711360):
Traceback (most recent call last):

  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "sscollector.pyz/">, '__spec__...
           │         └ <code object <module> at 0x7f81f08e1b30, file "sscollector.pyz/__main__.py", line 2>
           └ <function _run_code at 0x7f81f097fc10>
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "sscollector.pyz/">, '__spec__...
         └ <code object <module> at 0x7f81f08e1b30, file "sscollector.pyz/__main__.py", line 2>

  File "sscollector.pyz/__main__.py", line 3, in <module>

  File "sscollector.pyz/_bootstrap/__init__.py", line 233, in bootstrap

  File "sscollector.pyz/_bootstrap/__init__.py", line 36, in run

  File "/root/.shiv/sscollector_f1bc86a4f6f6fe47e7a3adca48b68f91357a3dc18de4c8a256722b4a00ef2273/site-packages/main.py", line 119, in main
    asyncio.run(run(args))
    │       │   │   └ Namespace(aad=False, auth='cli', azure=False, cloud='PUBLIC', config=None, get_creds=<function Context.auth at 0x7f81efcfe670...
    │       │   └ <function run at 0x7f81f02d10d0>
    │       └ <function run at 0x7f81f02b88b0>
    └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>

  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object run at 0x7f81eec06340>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f81f00119d0>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f81f0011940>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f81f00144c0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f81f00a23a0>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f81d43893d0>(<Future finished result=None>)>
> File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x7f81d43893d0>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x7f81d43893d0>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f81d43893d0>(<Future finished result=None>)>

  File "/root/.shiv/sscollector_f1bc86a4f6f6fe47e7a3adca48b68f91357a3dc18de4c8a256722b4a00ef2273/site-packages/stormcollector/aad.py", line 46, in query_objects
    parsedVal = await self.parse(value)
                      │    │     └ {'odata.type': 'Microsoft.DirectoryServices.Group', 'objectType': 'Group', 'objectId': 'abccfb09-8df9-48c7-b071-adf71f4f803f'...
                      │    └ <function AADGroup.parse at 0x7f81eed6dd30>
                      └ AADGroup(ctx=<stormcollector.auth.Context object at 0x7f81eebac1c0>, tenant_id='myorganization', base_url='https://graph.wind...

  File "/root/.shiv/sscollector_f1bc86a4f6f6fe47e7a3adca48b68f91357a3dc18de4c8a256722b4a00ef2273/site-packages/stormcollector/aad.py", line 123, in parse
    owner.get("objectId") or owner.get("id") for owner in owners["value"]
                                                          └ {'odata.error': {'code': 'Authentication_ExpiredToken', 'message': {'lang': 'en', 'value': 'Your access token has expired. Pl...

KeyError: 'value'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f81edb04a60>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f81edb2f880>, 373672.262163161)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f81edb1dbe0>
2020-09-09 13:30:33.365 | ERROR    | asyncio.events:_run:81 - An error has been caught in function '_run', process 'MainProcess' (5661), thread 'MainThread' (140196066711360):
Traceback (most recent call last):

  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
           │         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "sscollector.pyz/">, '__spec__...
           │         └ <code object <module> at 0x7f81f08e1b30, file "sscollector.pyz/__main__.py", line 2>
           └ <function _run_code at 0x7f81f097fc10>
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
         │     └ {'__name__': '__main__', '__doc__': None, '__package__': '', '__loader__': <zipimporter object "sscollector.pyz/">, '__spec__...
         └ <code object <module> at 0x7f81f08e1b30, file "sscollector.pyz/__main__.py", line 2>

  File "sscollector.pyz/__main__.py", line 3, in <module>

  File "sscollector.pyz/_bootstrap/__init__.py", line 233, in bootstrap

  File "sscollector.pyz/_bootstrap/__init__.py", line 36, in run

  File "/root/.shiv/sscollector_f1bc86a4f6f6fe47e7a3adca48b68f91357a3dc18de4c8a256722b4a00ef2273/site-packages/main.py", line 119, in main
    asyncio.run(run(args))
    │       │   │   └ Namespace(aad=False, auth='cli', azure=False, cloud='PUBLIC', config=None, get_creds=<function Context.auth at 0x7f81efcfe670...
    │       │   └ <function run at 0x7f81f02d10d0>
    │       └ <function run at 0x7f81f02b88b0>
    └ <module 'asyncio' from '/usr/lib/python3.8/asyncio/__init__.py'>

  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object run at 0x7f81eec06340>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f81f00119d0>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f81f0011940>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f81f00144c0>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f81f00a23a0>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f81d446e040>(<Future finished result=None>)>
> File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskWakeupMethWrapper object at 0x7f81d446e040>(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskWakeupMethWrapper object at 0x7f81d446e040>(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskWakeupMethWrapper object at 0x7f81d446e040>(<Future finished result=None>)>

  File "/root/.shiv/sscollector_f1bc86a4f6f6fe47e7a3adca48b68f91357a3dc18de4c8a256722b4a00ef2273/site-packages/stormcollector/aad.py", line 43, in query_objects
    raise Exception(response)
                    └ {'odata.error': {'code': 'Authentication_ExpiredToken', 'message': {'lang': 'en', 'value': 'Your access token has expired. Pl...

Exception: {'odata.error': {'code': 'Authentication_ExpiredToken', 'message': {'lang': 'en', 'value': 'Your access token has expired. Please renew it before submitting the request.'}}}
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f81edb84520>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f81ec295ca0>, 373676.563147996)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f81eebdd070>
2020-09-09 13:30:33.368 | INFO     | main:main:120 - Zipping up output...
2020-09-09 13:30:41.792 | INFO     | main:main:124 - --- COMPLETE: 3912.481698513031 seconds. OUTPUT: /stormspotter/stormcollector/results_20200909-122529.zip ---
```

**Comment by legra-ms** [comment]
Hi. This is a known issue as that occurs as a result of the access token expiring during long enumeration sessions, particularly using CLI credentials. 

What's happening is that the cli auth type uses the AzureCliCredential class of the Azure Identity SDK. This class subprocesses the `az` command and runs the `az` command for every request that goes out.  In order to minimize run times, the collector creates credentials before doing any sort of enumeration and uses that credential/access token for the duration of the enumeration. By default, an access token expires 60 minutes from creation. 

So what's happening here is that your access token is expiring during enumeration. The best workaround to approach this while I try to determine the best solution for refreshing the access token is to (assuming you have multiple subscriptions in your tenant) run the collector multiple times while specifying the subscriptions you are enumerating. 

`./sscollector.pyz cli --subs <sub1> <sub2> <sub3>`

**Comment by legra-ms** [comment]
After looking through the error a little further, it looks like your access token expired while enumerating AAD, so the sub parameters may not help you. There's currently no workaround for the issue for long AAD enumeration sessions so you'll have have to wait for the refresh implementation. 

An alternate method would be to use a Service Principal and grant it access to read your AAD objects, if you have the permissions to do so.

**Comment by mdaslamansari** [comment]
Thanks...can you please advise the timeline? Many thanks...

Also, I tried with SP and it created the results zip successfully. but when i am uploading it to FE, i m getting some issue. From where I can get the logs?

**Comment by legra-ms** [comment]
I don't have a timeline for a solution but it literally next on my list of things to address. For the sake of transparency, I'll find some time to put everything I have planned into the Projects tab on this repo.

You should be able to see live logs for the upload in the backend. Because some people may have massive files to upload, I haven't found a good way to reflect the status of the uploads on the frontend, but the backend logs should show everything that's happening.

**Comment by davidokeyode** [comment]
Having the same issue also. Stormcollector ran successfully but unable uploading to the FE wasn't successful
![image](https://user-images.githubusercontent.com/11473079/93120149-d2d8e080-f6ba-11ea-8d38-bf141972453a.png)

**Comment by legra-ms** [comment]
@davidokeyode Can you confirm that you actually have valid data in those sqlite files? That is a very small file size. 

This issue revolves around long running sessions (typically over an hour). I briefly spoke to someone who works on the Azure Identity SDK packaged and they mentioned that refreshing of access tokens is already being worked on for the various credential types they offer. This should ultimately resolve the issue here.

In the meantime, I've been attempting to do sort of a timed refresh in the collector code so that it just refreshes every 45 minutes transparently to the user but I've been unsuccessful so far. Still working on it though.

**Comment by legra-ms** [comment]
@davidokeyode Since you mentioned that you have a much smaller environment you were testing, your upload issue might not be related to this issue, so can you make a separate one? And we can walk through the backend logs to see what the problem might be (just make sure to sanitize the logs before posting 👀 ).

**Comment by davidokeyode** [comment]
> @davidokeyode Since you mentioned that you have a much smaller environment you were testing, your upload issue might not be related to this issue, so can you make a separate one? And we can walk through the backend logs to see what the problem might be (just make sure to sanitize the logs before posting 👀 ).

Thanks. Will you like me to open the issue or you can transfer my last note to an issue?

**Comment by davidokeyode** [comment]
> @davidokeyode Can you confirm that you actually have valid data in those sqlite files? That is a very small file size.
> 
> This issue revolves around long running sessions (typically over an hour). I briefly spoke to someone who works on the Azure Identity SDK packaged and they mentioned that refreshing of access tokens is already being worked on for the various credential types they offer. This should ultimately resolve the issue here.
> 
> In the meantime, I've been attempting to do sort of a timed refresh in the collector code so that it just refreshes every 45 minutes transparently to the user but I've been unsuccessful so far. Still working on it though.

Yes. Confirmed 
![image](https://user-images.githubusercontent.com/11473079/93126093-db81e480-f6c3-11ea-95ed-2b34f5859fd7.png)

**Comment by legra-ms** [comment]
FYI, after talking to the Azure Identity SDK team, they've discovered and resolved the issue with CLI credentials. (https://github.com/Azure/azure-sdk-for-python/issues/14345) It may be a little while before I can update and test but things are looking up. I don't have an estimate for this but I am hoping before the end of the month. I need to ensure that all aspects of the CLI refreshing are handled first.

**Comment by legra-ms** [comment]
AAD token refreshing has been added. Feel free to reopen this issue if you continue to get any sort of `Authentication_ExpiredToken` errors.
