### ISSUE TITLE
Not able to view any graph/resources on dashboard 

### ISSUE THREAD

**Issue by VaibhavVilasPandit** [Azure/Stormspotter#5]
After setting up Stormspotter in a virtual environment. I tried to gather resource and object information using both options (via cli login and via service principal). 

When tried to gather resources using command: stormspotter --service-principal -u <sp-id> -p <sp-secret> --tenant <tenant-id> it queries AADUser, AADGroup, AADServicePrincipal, AADApplication and it gives below output.

Attemprint to get CLI Credentials from a Service Principal
Attemprint to get CLI Credentials from a Service Principal
Starting query for AADUser
Starting query for AADGroup
Starting query for AADServicePrincipal
Starting query for AADApplication
'value'
'value'
'value'
'value'
Querying for resources in subscription id <subscription-id>
Getting rbac permissions for subscription: <subscription-id>
Getting management certs for subscription: <subscription-id>
Completion Time: 4.692746639251709
user or service principal does not have coadministrator access to subscription <subscription-id> to access management certs.
Finished management certs for subscription: <subscription-id>

and when we try using --cli command as stormspotter --cli or  stormspotter --cli --tenant <tenant-id> we get below output.

Attempting to get cli credentials for resource https://management.core.windows.net/
Attempting to get cli credentials for resource https://graph.windows.net/
Starting query for AADUser
Starting query for AADGroup
Starting query for AADServicePrincipal
Starting query for AADApplication
Finished query for AADApplication
Finished query for AADServicePrincipal
Finished query for AADUser
'value'
Completion Time: 3924.17653465271

Not sure, what's significance of 'value' if it's related to any error message. But post this when we try to load dashboard using stormdash it doesn;t show any graph/ resources as below.

![image](https://user-images.githubusercontent.com/39079193/83037534-cfe6b100-a033-11ea-9bd9-8d3275c7b962.png)

1. Do we need coadministrator access to service principal over subscription here ?
2. We have followed steps mentioned in readme, are we missing any steps here ?
3. Are there any other steps/ access required to be get the graph loaded ?

**Comment by legra-ms** [comment]
Hi.

Those value strings are probably errors that occurred. I'm not entirely sure why 'value' printed as opposed to the actual error but I'll try to look into it. 

Also, it looks like those errors caused Stormspotter to think it finished early, as indicated by the fact that you were still getting messages after "Completion" time. This might be because of the current ThreadPoolExecutor implementation. I'll look into this but I do plan to rewrite all of this in `async` properly so that shouldn't be an issue before the full release.

To answer your questions:

No, you do not need coadmin access. That message is a result of looking for management certs on your subscription and your credentials do not have access to read those, if there are any to begin with.

It appears you've done things correctly, but can you confirm that you actually have the full set of files in your results.zip? You should see `subdata.json`, `rbac.json`, a couple of AAD json files, and one file per subscription id.

**Comment by VaibhavVilasPandit** [comment]
@legra-ms Thanks for your update.

Reg Results.zip, I can see only AAD files in it as AADApplication, AADServicePrincipal, AADUser and couldn't find subdata.json, rbac.json.

**Comment by legra-ms** [comment]
@VaibhavVilasPandit Sorry for the long response time. 

It turns out a possible reason you may be getting "value" is because the credentials you used do not have subscription level access. If you log into Azure with `az cli` or `Connect-AzAccount` do you have any subscriptions that are listed?

**Comment by VaibhavVilasPandit** [comment]
@legra-ms Yes, The service principal which I used for this has access to our subscription. As you have asked and just to confirm, I ran the Connect-AzAccount with same sp and it returns the subscription.
The value error was seen for --cli command too where it used mine az login and I have access to multiple subscriptions.
Let me know if you need any further details.

**Comment by mdaslamansari** [comment]
Any updates on it...I am also facing same issue.

**Comment by legra-ms** [comment]
While building the new version of the collector, I came across this same issue with more details. The Service Principal did not have Directory.Read permissions to Azure AD Graph (https:.//graph.windows.net). Instead, when the SPN was created, it defaulted to the newer https://graph.microsoft.com endpoint. That printout of "value" was an error occurring when making a call to graph.windows.net and the error was not caught correctly.

The API used for graph.windows.net gives more information about AAD objects than graph.microsoft.com does. As the new version of the collector gets built, I'm going to try to find a way to deal with this issue in a better way.

**Comment by legra-ms** [comment]
@VaibhavVilasPandit @mdaslamansari Please feel free to test out this new collector package against your subscriptions. Command line options have changed. Keep mind of the note that the results from this package can't be used in the existing Stormdash.

https://github.com/Azure/Stormspotter/releases/tag/v1.0.0-beta

**Comment by legra-ms** [comment]
Closing this as this issue should no longer applicable with the new beta release.
