### ISSUE TITLE
Command not found error when running stormdash.py

### ISSUE THREAD

**Issue by alimukarramm** [Azure/Stormspotter#6]
Hi, I am having below error when running ""stormdash.py"" however no issue when I run the command ""root@kali:/opt/Stormspotter# ./Stormspotter.py --cli""

root@kali:/opt/Stormspotter# ./Stormdash.py -dbu neo4j -dbp *******
./Stormdash.py: line 1: import: command not found
./Stormdash.py: line 2: import: command not found
./Stormdash.py: line 3: import: command not found
./Stormdash.py: line 4: import: command not found
./Stormdash.py: line 5: import: command not found
from: can't read /var/mail/pathlib
from: can't read /var/mail/pprint
from: can't read /var/mail/dash.dependencies
from: can't read /var/mail/dash.exceptions
from: can't read /var/mail/stormspotter.dash.layout.cytoscape
from: can't read /var/mail/stormspotter.dash.layout.ui
from: can't read /var/mail/stormspotter.dash.core.context
from: can't read /var/mail/stormspotter.dash.core.parsers
./Stormdash.py: line 17: parser: command not found
./Stormdash.py: line 18: syntax error near unexpected token `('
./Stormdash.py: line 18: `app = dash.Dash(__name__, assets_folder=Path("stormspotter/dash/assets").absolute())'

Please help...

**Comment by legra-ms** [comment]
Hi. 

This looks like an issue with your environment. Since you are running the python scripts directly, you should either make sure the scripts have the executable bit set (`chmod +x`) or you can run it as `python stormspotter.py`.

**Comment by ndrix** [comment]
It seems that stormdash didn't have a shebang - so running it as ./stormdash.py would see it as bash (/zsh, whatever your shell is) file.  

Created a PR for that
