### ISSUE TITLE
Fixed context.py: KeyError: 'availabilitySet'

### ISSUE THREAD

**Issue by m8r1us** [Azure/Stormspotter#8]
Pull requests not working for me so adding it to here:

If VM's have availability sets configured, stormdash.py crashed with the error: "KeyError: 'availabilitySet'

Fixed by opening context.py under /stormspotter/dash/core/ and adding ["properties"] in line 319:
vmas_id = vm["properties"]["availabilitySet"]["id"]

**Comment by daddycocoaman** [comment]
Thanks! Someone else just hit me with this today and I'm addressing it now.

Also, the PR issue might be due to the new requirements for interacting with repos.
